name=Jandula_Base
version=1.0.0
author=Francisco Manuel Benítez Chico
maintainer=Francisco Manuel Benítez Chico
sentence=Librería base para aquellas funcionalidades básicas a todos los microcontroladores
paragraph=JWT, WiFi, LittleFS, SD y NTP
category=Other
architectures=esp32
